dataset_type: 'default'
replay_dataset_path: 'your_path_here'
ataripb_dataset_path: './materials/dataset'
ataripb_subdir_name: 'train'

games: ['air_raid', 'amidar', 'asteroids', 'atlantis', 'bank_heist', 
        'battle_zone', 'berzerk', 'bowling', 'boxing', 'breakout', 
        'carnival', 'centipede', 'chopper_command', 'crazy_climber', 'demon_attack', 
        'double_dunk', 'elevator_action', 'enduro', 'fishing_derby', 'freeway', 
        'frostbite', 'gopher', 'gravitar', 'hero', 'ice_hockey', 
        'jamesbond', 'kangaroo', 'krull', 'kung_fu_master', 'montezuma_revenge', 
        'ms_pacman', 'name_this_game', 'phoenix', 'pitfall', 'private_eye', 
        'qbert', 'road_runner', 'robotank', 'skiing', 'solaris', 
        'space_invaders', 'star_gunner', 'tennis', 'time_pilot', 'tutankham', 
        'up_n_down', 'video_pinball', 'wizard_of_wor', 'yars_revenge', 'zaxxon']
runs: [1, 2]
checkpoints: [1,2,3,4,5,6,7,8,9,10]
samples_per_checkpoint: 10000

minimal_action_set: True  # whether the dataset was minimal action set 

num_workers: ${eval:${num_gpus_per_node}*4} # 0 = load data in main process
pin_memory: True
prefetch_factor: 2 # num_workers*prefetch_factor will be prefetched

distributed: False

batch_size: 512
t_step: 1
n_step: 3 # number of added step (similar to n_step in RL)
gamma: 0.99
frame: 4
shuffle: True
eval_ratio: 0.01 # [0,1]