type: dt_neck
in_shape: null
action_size: null
num_heads: 60 # number of games
norm_type: 'ln'
hidden_dims: [1024, 512]
t_step: ${dataloader.t_step}

transformer_encoder:
  dim: ${model.dt_embed_dim} # embed dim
  mlp_dim: ${model.dt_mlp_dim} # mlp ratio = 4.0
  depth: 4 # num layers 
  heads: 4 # num heads
