project_name: 'atari_bench_zeroshot'
entity: 'your_wandb_entity_here'
group_name: 'test'
exp_name: 'test'
wandb_run_name: null

# parallel training
# seeds: number of different seeds to run
seeds: [0,1,2] 
num_nodes: 1
num_gpus_per_node: 2
num_exps_per_gpu: 2
rank: 0

# each run
device: null
seed: null

defaults:
- _self_
- dataloader: zeroshot
- trainer: base 
- env: atari
- model: base
- pretrained: load_bnh_freeze_bnh
